/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const showConfirmDialog: typeof import('vant/es')['showConfirmDialog']
  const showFailToast: typeof import('vant/es')['showFailToast']
  const showLoadingToast: typeof import('vant/es')['showLoadingToast']
  const showSuccessToast: typeof import('vant/es')['showSuccessToast']
  const showToast: typeof import('vant/es')['showToast']
}
