/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Buttombar: typeof import('./src/components/buttombar.vue')['default']
    Firecard: typeof import('./src/components/homecom/firecard.vue')['default']
    Focuscard: typeof import('./src/components/homecom/focuscard.vue')['default']
    Headimg: typeof import('./src/components/topbar/headimg.vue')['default']
    Homecard: typeof import('./src/components/homecom/homecard.vue')['default']
    Postcard: typeof import('./src/components/postcard.vue')['default']
    Publishicon: typeof import('./src/components/topbar/publishicon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/topbar/search.vue')['default']
    Subject: typeof import('./src/components/homecom/subject.vue')['default']
    Swipe: typeof import('./src/components/homecom/swipe.vue')['default']
    Tbs: typeof import('./src/components/topbar/tbs.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSearch: typeof import('vant/es')['Search']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    Xinxi: typeof import('./src/components/homecom/xinxi.vue')['default']
  }
}
