/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Buttombar: typeof import('./src/components/buttombar.vue')['default']
    Firecard: typeof import('./src/components/homecom/firecard.vue')['default']
    Focus: typeof import('./src/components/homecom/focus.vue')['default']
    Focuscard: typeof import('./src/components/homecom/focuscard.vue')['default']
    Headimg: typeof import('./src/components/topbar/headimg.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Homecard: typeof import('./src/components/homecom/homecard.vue')['default']
    Indextopbar: typeof import('./src/components/bra/homebar/indextopbar.vue')['default']
    Postcard: typeof import('./src/components/postcard.vue')['default']
    Publishicon: typeof import('./src/components/topbar/publishicon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/topbar/search.vue')['default']
    Sourcetopbar: typeof import('./src/components/sourcebar/sourcetopbar.vue')['default']
    Subject: typeof import('./src/components/homecom/subject.vue')['default']
    Swipe: typeof import('./src/components/homecom/swipe.vue')['default']
    Tabbra: typeof import('./src/components/tabbra/tabbra.vuebra.vue')['default']
    Tbs: typeof import('./src/components/topbar/tbs.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSSticky: typeof import('vant/es')['SSticky']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
