/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Buttom: typeof import('./src/components/tabbra/buttom.vue')['default']
    Buttombar: typeof import('./src/components/bra/buttombar.vue')['default']
    Buttombat: typeof import('./src/components/tabbra/buttombat.vue')['default']
    Comment: typeof import('./src/components/comment.vue')['default']
    Headimg: typeof import('./src/components/bra/topbar/headimg.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Homecard: typeof import('./src/components/bra/indexbar/homecard.vue')['default']
    Indextopbar: typeof import('./src/components/bra/indexbar/indextopbar.vue')['default']
    Maintopbar: typeof import('./src/components/bra/mainbar/maintopbar.vue')['default']
    Postcard: typeof import('./src/components/postcard.vue')['default']
    Publishicon: typeof import('./src/components/bra/topbar/publishicon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/bra/topbar/search.vue')['default']
    Sourcetopbar: typeof import('./src/components/bra/sourcebar/sourcetopbar.vue')['default']
    Swipe: typeof import('./src/components/bra/indexbar/swipe.vue')['default']
    Tabbra: typeof import('./src/components/tabbra/index.vue')['default']
    Tbs: typeof import('./src/components/bra/topbar/tbs.vue')['default']
    Top: typeof import('./src/components/tabbra/top.vue')['default']
    Topbar: typeof import('./src/components/bra/indexbar/topbar.vue')['default']
    Topbat: typeof import('./src/components/tabbra/topbat.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanField: typeof import('vant/es')['Field']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanSearch: typeof import('vant/es')['Search']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
